version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/.Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/.Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    external: true
   